
-- 1. Backup: Rename the old table if it exists (just in case), or Drop it.
drop table if exists public.stories cascade;

-- 2. Create the 'stories' table (Using "description" instead of "desc")
create table public.stories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text, -- Changed from "desc" to "description"
  tag text,
  duration text, 
  color text default 'bg-pink-100', 
  icon text, 
  audio_url text,
  image_url text
);

-- 3. Enable RLS
alter table public.stories enable row level security;

-- 4. Create Policies
create policy "Public stories are viewable by everyone"
  on public.stories for select
  using ( true );

create policy "Authenticated users can manage stories"
  on public.stories for all
  using ( auth.role() = 'authenticated' );

-- 5. Seed Data (Insert the Mock Stories)
insert into public.stories (title, duration, color, icon, description, tag, audio_url)
values 
('Pip''s Big Parade', '12 min', 'bg-purple-100', '🐘', 'Pip finds his courage when the big parade comes to town.', 'Social Skills', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'),
('Lila & The Ocean Song', '15 min', 'bg-blue-100', '🌊', 'A calming journey to the bottom of the deep blue sea.', 'Mindfulness', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3'),
('The Sleepy Moon', '20 min', 'bg-indigo-100', '🌙', 'Perfect for bedtime. Say goodnight to the stars with Moon.', 'Bedtime', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3'),
('Leo''s Lost Roar', '10 min', 'bg-orange-100', '🦁', 'Leo wakes up with a squeak instead of a roar! What will he do?', 'Emotions', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3'),
('The Sharing Tree', '14 min', 'bg-green-100', '🌳', 'A magical tree teaches the forest animals about kindness.', 'Kindness', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3'),
('Ruby''s Rainy Day', '8 min', 'bg-red-100', '☔', 'Ruby learns that rainy days can be just as fun as sunny ones.', 'Optimism', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3'),
('The Magic Paintbrush', '10 min', 'bg-red-100', '🎨', 'Everything painted comes to life!', 'Creativity', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3'),
('Benny''s Balloon Ride', '15 min', 'bg-sky-100', '🎈', 'Up, up and away into the clouds.', 'Adventure', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3'),
('Detective Fox', '12 min', 'bg-orange-100', '🦊', 'Solving the mystery of the missing pie.', 'Problem Solving', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3');

-- 6. Storage Bucket (Idempotent)
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do nothing;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'uploads' );

create policy "Authenticated Uploads"
  on storage.objects for insert
  with check ( bucket_id = 'uploads' and auth.role() = 'authenticated' );
