
-- 1. Create Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null default 0.00,
  image_url text,
  stock_status text default 'In Stock', -- 'In Stock', 'Out of Stock'
  category text default 'General'
);

-- 2. Security Policies
alter table public.products enable row level security;

-- Everyone can see products
create policy "Public products are viewable by everyone"
  on public.products for select
  using ( true );

-- Authenticated users (Admins) can Manage (Insert, Update, Delete)
-- Ideally use the 'admin' role check, but 'authenticated' is fine for this MVP step
create policy "Admins can manage products"
  on public.products for all
  using ( auth.role() = 'authenticated' );
