-- 1. Create the 'stories' table
create table public.stories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  desc text,
  tag text,
  duration text, -- e.g. "5 min"
  color text default 'bg-pink-100', -- e.g. Tailwind class
  icon text, -- e.g. "🦁" (emoji) or URL
  audio_url text,
  image_url text
);

-- 2. Enable Row Level Security (RLS)
alter table public.stories enable row level security;

-- 3. Create Policies
-- Allow anyone to READ stories (public catalog)
create policy "Public stories are viewable by everyone"
  on public.stories for select
  using ( true );

-- Allow authenticated users (Admins) to INSERT/UPDATE/DELETE
-- Note: In a real production app, you'd stricter checks here (e.g. check for admin role)
-- For this MVP, we allow any logged-in user to edit, or you can toggle this to true for testing.
create policy "Authenticated users can manage stories"
  on public.stories for all
  using ( auth.role() = 'authenticated' );

-- 4. Create Storage Bucket for Uploads
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true);

-- 5. Storage Policies
-- Allow public access to view files
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'uploads' );

-- Allow authenticated users to upload
create policy "Authenticated Uploads"
  on storage.objects for insert
  with check ( bucket_id = 'uploads' and auth.role() = 'authenticated' );
