
-- Ensure Products table exists
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null default 0.00,
  image_url text,
  stock_status text default 'In Stock',
  category text default 'General'
);

-- Reset RLS for Products to be permissive for authenticated users
alter table public.products enable row level security;

drop policy if exists "Admins can manage products" on public.products;
drop policy if exists "Public products are viewable by everyone" on public.products;

create policy "Public products are viewable by everyone"
  on public.products for select
  using ( true );

create policy "Authenticated users can manage products"
  on public.products for all
  using ( auth.role() = 'authenticated' );
